# Generated by Django 5.1.7 on 2025-10-17 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_service_user_service_operator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='operator',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='head',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Руководитель поставщика услуг (будет отображаться в акте выполненных работ)'),
            preserve_default=False,
        ),
    ]
