# Generated by Django 5.2.1 on 2026-07-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_service_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип объекта ИС',
                'verbose_name_plural': 'Типы объектов ИС',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectsCatalogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_hero_image', models.ImageField(blank=True, null=True, upload_to='catalog_heroes/', verbose_name='Картинка героя (Проекты)')),
                ('patents_hero_image', models.ImageField(blank=True, help_text='Эта картинка показывается во вкладке «Интеллектуальная собственность»', null=True, upload_to='catalog_heroes/', verbose_name='Картинка героя (Патенты / ИС)')),
                ('projects_lead', models.TextField(blank=True, help_text='Если пусто — используется текст по умолчанию из переводов', verbose_name='Текст под заголовком (Проекты)')),
                ('projects_lead_ru', models.TextField(blank=True, help_text='Если пусто — используется текст по умолчанию из переводов', null=True, verbose_name='Текст под заголовком (Проекты)')),
                ('projects_lead_kk', models.TextField(blank=True, help_text='Если пусто — используется текст по умолчанию из переводов', null=True, verbose_name='Текст под заголовком (Проекты)')),
                ('projects_lead_en', models.TextField(blank=True, help_text='Если пусто — используется текст по умолчанию из переводов', null=True, verbose_name='Текст под заголовком (Проекты)')),
                ('patents_lead', models.TextField(blank=True, help_text='Если пусто — используется текст по умолчанию из переводов', verbose_name='Текст под заголовком (Патенты / ИС)')),
                ('patents_lead_ru', models.TextField(blank=True, help_text='Если пусто — используется текст по умолчанию из переводов', null=True, verbose_name='Текст под заголовком (Патенты / ИС)')),
                ('patents_lead_kk', models.TextField(blank=True, help_text='Если пусто — используется текст по умолчанию из переводов', null=True, verbose_name='Текст под заголовком (Патенты / ИС)')),
                ('patents_lead_en', models.TextField(blank=True, help_text='Если пусто — используется текст по умолчанию из переводов', null=True, verbose_name='Текст под заголовком (Патенты / ИС)')),
            ],
            options={
                'verbose_name': 'Настройки каталога проектов',
                'verbose_name_plural': 'Настройки каталога проектов',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='client_problem',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки (для детальной страницы)', verbose_name='Проблема клиента'),
        ),
        migrations.AddField(
            model_name='project',
            name='our_solution',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки (для детальной страницы)', verbose_name='Наше решение'),
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Название')),
                ('title_kk', models.CharField(max_length=300, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL slug')),
                ('registration_number', models.CharField(blank=True, help_text='Например: № 34567', max_length=100, verbose_name='Номер регистрации')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('short_description_ru', models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание')),
                ('short_description_kk', models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание')),
                ('short_description_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('benefits', models.TextField(blank=True, help_text='Каждый пункт с новой строки', verbose_name='Что получает заказчик')),
                ('benefits_ru', models.TextField(blank=True, help_text='Каждый пункт с новой строки', null=True, verbose_name='Что получает заказчик')),
                ('benefits_kk', models.TextField(blank=True, help_text='Каждый пункт с новой строки', null=True, verbose_name='Что получает заказчик')),
                ('benefits_en', models.TextField(blank=True, help_text='Каждый пункт с новой строки', null=True, verbose_name='Что получает заказчик')),
                ('document', models.FileField(blank=True, null=True, upload_to='patent_docs/', verbose_name='Документ для скачивания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('patent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='main_app.patenttype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Патент / объект ИС',
                'verbose_name_plural': 'Патенты / объекты ИС',
                'ordering': ['order', '-registration_date', '-created_at'],
            },
        ),
    ]
