# Generated by Django 5.2.1 on 2026-07-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_patents_and_catalog_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Отдел команды',
                'verbose_name_plural': 'Отделы команды',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('position', models.CharField(max_length=250, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=250, null=True, verbose_name='Должность')),
                ('position_kk', models.CharField(max_length=250, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=250, null=True, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите фото сюда (приоритетнее ссылки и static)', null=True, upload_to='team_members/', verbose_name='Фото')),
                ('external_photo', models.URLField(blank=True, help_text='Если фото на внешнем сайте', verbose_name='Ссылка на фото')),
                ('static_photo', models.CharField(blank=True, help_text='Например: images/team/agrotechnopark/Agrotechnopark2.webp', max_length=255, verbose_name='Путь static')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_leadership', models.BooleanField(default=False, help_text='Крупная карточка с контактами', verbose_name='Руководство')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main_app.teamdepartment', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Команда',
                'ordering': ['order', 'name'],
            },
        ),
    ]
