# Generated by Django 5.2.1 on 2026-07-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_team_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Сотрудник (страница Команда)', 'verbose_name_plural': 'Команда (сотрудники)'},
        ),
        migrations.AddField(
            model_name='patent',
            name='application_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заявки'),
        ),
        migrations.AddField(
            model_name='patent',
            name='authors',
            field=models.CharField(blank=True, max_length=300, verbose_name='Авторы / правообладатель'),
        ),
        migrations.AddField(
            model_name='patent',
            name='icon',
            field=models.ImageField(blank=True, help_text='Круглая картинка слева на карточке', null=True, upload_to='patent_icons/', verbose_name='Иконка / логотип'),
        ),
        migrations.AddField(
            model_name='patent',
            name='is_active_status',
            field=models.BooleanField(default=True, help_text='Показывать статус «Действует»', verbose_name='Действует'),
        ),
        migrations.AddField(
            model_name='patent',
            name='read_url',
            field=models.URLField(blank=True, verbose_name='Ссылка «Читать патент»'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='document',
            field=models.FileField(blank=True, help_text='Кнопка «Скачать PDF»', null=True, upload_to='patent_docs/', verbose_name='PDF / документ'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Например: № 17350', max_length=100, verbose_name='Номер'),
        ),
    ]
