# Generated by Django 5.2.1 on 2026-07-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_patent_card_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='country',
            field=models.CharField(blank=True, default='Казахстан', max_length=100, verbose_name='Страна'),
        ),
    ]
