# Generated by Django 5.2.1 on 2026-07-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_patent_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='badge_letter',
            field=models.CharField(blank=True, help_text='Если иконка не загружена. Например: C, П', max_length=2, verbose_name='Буква на иконке'),
        ),
    ]
