# Generated by Django 5.2.1 on 2026-09-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_hub_request_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralRequestProxy',
            fields=[
            ],
            options={
                'verbose_name': 'General Request',
                'verbose_name_plural': 'General Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.servicerequest',),
        ),
        migrations.CreateModel(
            name='ProjectCollaborationRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Project Collaboration Request',
                'verbose_name_plural': 'Project Collaboration Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.servicerequest',),
        ),
        migrations.CreateModel(
            name='ProjectProposalRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Project Proposal',
                'verbose_name_plural': 'Project Proposals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.servicerequest',),
        ),
        migrations.CreateModel(
            name='ServiceRequestProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.servicerequest',),
        ),
    ]
