# Generated by Django 5.2.1 on 2026-09-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_generalrequestproxy_projectcollaborationrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationOfficeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Организация')),
                ('division', models.CharField(blank=True, max_length=300, verbose_name='Подразделение')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('lead', models.TextField(blank=True, verbose_name='Описание блока')),
            ],
            options={
                'verbose_name': 'Офис инноваций — контакты',
                'verbose_name_plural': 'Офис инноваций — контакты',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='contact_address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='course',
            name='contact_division',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='course',
            name='contact_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='course',
            name='contact_org',
            field=models.CharField(blank=True, max_length=200, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='course',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='course',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_division',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_org',
            field=models.CharField(blank=True, max_length=200, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='contact_address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='contact_division',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='contact_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='contact_org',
            field=models.CharField(blank=True, max_length=200, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
    ]
