# Generated by Django 5.2.1 on 2026-09-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_service_contact_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_problem_en',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки (для детальной страницы)', null=True, verbose_name='Проблема клиента'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_problem_kk',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки (для детальной страницы)', null=True, verbose_name='Проблема клиента'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_problem_ru',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки (для детальной страницы)', null=True, verbose_name='Проблема клиента'),
        ),
        migrations.AddField(
            model_name='project',
            name='our_solution_en',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки (для детальной страницы)', null=True, verbose_name='Наше решение'),
        ),
        migrations.AddField(
            model_name='project',
            name='our_solution_kk',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки (для детальной страницы)', null=True, verbose_name='Наше решение'),
        ),
        migrations.AddField(
            model_name='project',
            name='our_solution_ru',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки (для детальной страницы)', null=True, verbose_name='Наше решение'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(blank=True, help_text='Каждая технология с новой строки (вкладка «Технологии»)', verbose_name='Технологии'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_en',
            field=models.TextField(blank=True, help_text='Каждая технология с новой строки (вкладка «Технологии»)', null=True, verbose_name='Технологии'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_kk',
            field=models.TextField(blank=True, help_text='Каждая технология с новой строки (вкладка «Технологии»)', null=True, verbose_name='Технологии'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_ru',
            field=models.TextField(blank=True, help_text='Каждая технология с новой строки (вкладка «Технологии»)', null=True, verbose_name='Технологии'),
        ),
        migrations.CreateModel(
            name='ProjectContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_kk', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('body_ru', models.TextField(null=True, verbose_name='Текст')),
                ('body_kk', models.TextField(null=True, verbose_name='Текст')),
                ('body_en', models.TextField(null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, help_text='Необязательно. Если фото нет — текст на всю ширину.', null=True, upload_to='project_content/', verbose_name='Фото')),
                ('image_placement', models.CharField(choices=[('right', 'Справа от текста'), ('below', 'Снизу под текстом')], default='right', help_text='Справа от текста или снизу.', max_length=10, verbose_name='Расположение фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='main_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Блок «О проекте»',
                'verbose_name_plural': 'Блоки «О проекте»',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectResultMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Подпись')),
                ('label_ru', models.CharField(max_length=200, null=True, verbose_name='Подпись')),
                ('label_kk', models.CharField(max_length=200, null=True, verbose_name='Подпись')),
                ('label_en', models.CharField(max_length=200, null=True, verbose_name='Подпись')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('value_ru', models.CharField(max_length=100, null=True, verbose_name='Значение')),
                ('value_kk', models.CharField(max_length=100, null=True, verbose_name='Значение')),
                ('value_en', models.CharField(max_length=100, null=True, verbose_name='Значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_metrics', to='main_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Метрика результата',
                'verbose_name_plural': 'Метрики результатов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectResultTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок таблицы')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок таблицы')),
                ('title_kk', models.CharField(max_length=200, null=True, verbose_name='Заголовок таблицы')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок таблицы')),
                ('table_data', models.TextField(help_text='Первая строка — заголовки через |, далее строки через |. Пример:\nПараметр|Значение\nУрожайность|+35%', verbose_name='Данные таблицы')),
                ('table_data_ru', models.TextField(help_text='Первая строка — заголовки через |, далее строки через |. Пример:\nПараметр|Значение\nУрожайность|+35%', null=True, verbose_name='Данные таблицы')),
                ('table_data_kk', models.TextField(help_text='Первая строка — заголовки через |, далее строки через |. Пример:\nПараметр|Значение\nУрожайность|+35%', null=True, verbose_name='Данные таблицы')),
                ('table_data_en', models.TextField(help_text='Первая строка — заголовки через |, далее строки через |. Пример:\nПараметр|Значение\nУрожайность|+35%', null=True, verbose_name='Данные таблицы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_tables', to='main_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Таблица результатов',
                'verbose_name_plural': 'Таблицы результатов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка на видео (YouTube и т.п.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Видео проекта',
                'verbose_name_plural': 'Видео проектов',
                'ordering': ['order', 'id'],
            },
        ),
    ]
