# Generated by Django 5.2.1 on 2026-09-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_project_result_table_rows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcontentblock',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Контент-блок проекта', 'verbose_name_plural': 'Контент-блоки проекта'},
        ),
        migrations.AddField(
            model_name='projectcontentblock',
            name='section',
            field=models.CharField(choices=[('about', 'О проекте'), ('results', 'Результаты')], default='about', help_text='Где показывать блок на странице проекта.', max_length=20, verbose_name='Вкладка'),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='image',
            field=models.ImageField(blank=True, help_text='Необязательно. Если фото нет — текст на всю ширину контейнера.', null=True, upload_to='project_content/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='projectcontentblock',
            name='image_placement',
            field=models.CharField(choices=[('right', 'Справа от текста'), ('below', 'Снизу под текстом')], default='right', help_text='Справа от текста или снизу. Игнорируется, если фото не загружено.', max_length=10, verbose_name='Расположение фото'),
        ),
    ]
